# Derived from PostgreSQL 18.6, src/include/parser/kwlist.h.
#
# PostgreSQL Database Management System
# (also known as Postgres, formerly known as Postgres95)
#
# Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
#
# Portions Copyright (c) 1994, The Regents of the University of California
#
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose, without fee, and without a written agreement
# is hereby granted, provided that the above copyright notice and this
# paragraph and the following two paragraphs appear in all copies.
#
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
# DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
# LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS
# DOCUMENTATION, EVEN IF THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
# ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATIONS TO
# PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.

## Postgres 18's keywords, in the order of `src/include/parser/kwlist.h`:
## the text, the grammar's token name, the category that decides where the
## grammar accepts it as a name, and whether it may be a column label
## without `AS`.
Keywords :: [].{
	Category : [Unreserved, ColName, TypeFuncName, Reserved]

	Keyword : { name : Str, token : Str, category : Keywords.Category, bare_label : Bool }

	all : List(Keywords.Keyword)
	all = [
		{ name: "abort", token: "ABORT_P", category: Unreserved, bare_label: Bool.True },
		{ name: "absent", token: "ABSENT", category: Unreserved, bare_label: Bool.True },
		{ name: "absolute", token: "ABSOLUTE_P", category: Unreserved, bare_label: Bool.True },
		{ name: "access", token: "ACCESS", category: Unreserved, bare_label: Bool.True },
		{ name: "action", token: "ACTION", category: Unreserved, bare_label: Bool.True },
		{ name: "add", token: "ADD_P", category: Unreserved, bare_label: Bool.True },
		{ name: "admin", token: "ADMIN", category: Unreserved, bare_label: Bool.True },
		{ name: "after", token: "AFTER", category: Unreserved, bare_label: Bool.True },
		{ name: "aggregate", token: "AGGREGATE", category: Unreserved, bare_label: Bool.True },
		{ name: "all", token: "ALL", category: Reserved, bare_label: Bool.True },
		{ name: "also", token: "ALSO", category: Unreserved, bare_label: Bool.True },
		{ name: "alter", token: "ALTER", category: Unreserved, bare_label: Bool.True },
		{ name: "always", token: "ALWAYS", category: Unreserved, bare_label: Bool.True },
		{ name: "analyse", token: "ANALYSE", category: Reserved, bare_label: Bool.True },
		{ name: "analyze", token: "ANALYZE", category: Reserved, bare_label: Bool.True },
		{ name: "and", token: "AND", category: Reserved, bare_label: Bool.True },
		{ name: "any", token: "ANY", category: Reserved, bare_label: Bool.True },
		{ name: "array", token: "ARRAY", category: Reserved, bare_label: Bool.False },
		{ name: "as", token: "AS", category: Reserved, bare_label: Bool.False },
		{ name: "asc", token: "ASC", category: Reserved, bare_label: Bool.True },
		{ name: "asensitive", token: "ASENSITIVE", category: Unreserved, bare_label: Bool.True },
		{ name: "assertion", token: "ASSERTION", category: Unreserved, bare_label: Bool.True },
		{ name: "assignment", token: "ASSIGNMENT", category: Unreserved, bare_label: Bool.True },
		{ name: "asymmetric", token: "ASYMMETRIC", category: Reserved, bare_label: Bool.True },
		{ name: "at", token: "AT", category: Unreserved, bare_label: Bool.True },
		{ name: "atomic", token: "ATOMIC", category: Unreserved, bare_label: Bool.True },
		{ name: "attach", token: "ATTACH", category: Unreserved, bare_label: Bool.True },
		{ name: "attribute", token: "ATTRIBUTE", category: Unreserved, bare_label: Bool.True },
		{ name: "authorization", token: "AUTHORIZATION", category: TypeFuncName, bare_label: Bool.True },
		{ name: "backward", token: "BACKWARD", category: Unreserved, bare_label: Bool.True },
		{ name: "before", token: "BEFORE", category: Unreserved, bare_label: Bool.True },
		{ name: "begin", token: "BEGIN_P", category: Unreserved, bare_label: Bool.True },
		{ name: "between", token: "BETWEEN", category: ColName, bare_label: Bool.True },
		{ name: "bigint", token: "BIGINT", category: ColName, bare_label: Bool.True },
		{ name: "binary", token: "BINARY", category: TypeFuncName, bare_label: Bool.True },
		{ name: "bit", token: "BIT", category: ColName, bare_label: Bool.True },
		{ name: "boolean", token: "BOOLEAN_P", category: ColName, bare_label: Bool.True },
		{ name: "both", token: "BOTH", category: Reserved, bare_label: Bool.True },
		{ name: "breadth", token: "BREADTH", category: Unreserved, bare_label: Bool.True },
		{ name: "by", token: "BY", category: Unreserved, bare_label: Bool.True },
		{ name: "cache", token: "CACHE", category: Unreserved, bare_label: Bool.True },
		{ name: "call", token: "CALL", category: Unreserved, bare_label: Bool.True },
		{ name: "called", token: "CALLED", category: Unreserved, bare_label: Bool.True },
		{ name: "cascade", token: "CASCADE", category: Unreserved, bare_label: Bool.True },
		{ name: "cascaded", token: "CASCADED", category: Unreserved, bare_label: Bool.True },
		{ name: "case", token: "CASE", category: Reserved, bare_label: Bool.True },
		{ name: "cast", token: "CAST", category: Reserved, bare_label: Bool.True },
		{ name: "catalog", token: "CATALOG_P", category: Unreserved, bare_label: Bool.True },
		{ name: "chain", token: "CHAIN", category: Unreserved, bare_label: Bool.True },
		{ name: "char", token: "CHAR_P", category: ColName, bare_label: Bool.False },
		{ name: "character", token: "CHARACTER", category: ColName, bare_label: Bool.False },
		{ name: "characteristics", token: "CHARACTERISTICS", category: Unreserved, bare_label: Bool.True },
		{ name: "check", token: "CHECK", category: Reserved, bare_label: Bool.True },
		{ name: "checkpoint", token: "CHECKPOINT", category: Unreserved, bare_label: Bool.True },
		{ name: "class", token: "CLASS", category: Unreserved, bare_label: Bool.True },
		{ name: "close", token: "CLOSE", category: Unreserved, bare_label: Bool.True },
		{ name: "cluster", token: "CLUSTER", category: Unreserved, bare_label: Bool.True },
		{ name: "coalesce", token: "COALESCE", category: ColName, bare_label: Bool.True },
		{ name: "collate", token: "COLLATE", category: Reserved, bare_label: Bool.True },
		{ name: "collation", token: "COLLATION", category: TypeFuncName, bare_label: Bool.True },
		{ name: "column", token: "COLUMN", category: Reserved, bare_label: Bool.True },
		{ name: "columns", token: "COLUMNS", category: Unreserved, bare_label: Bool.True },
		{ name: "comment", token: "COMMENT", category: Unreserved, bare_label: Bool.True },
		{ name: "comments", token: "COMMENTS", category: Unreserved, bare_label: Bool.True },
		{ name: "commit", token: "COMMIT", category: Unreserved, bare_label: Bool.True },
		{ name: "committed", token: "COMMITTED", category: Unreserved, bare_label: Bool.True },
		{ name: "compression", token: "COMPRESSION", category: Unreserved, bare_label: Bool.True },
		{ name: "concurrently", token: "CONCURRENTLY", category: TypeFuncName, bare_label: Bool.True },
		{ name: "conditional", token: "CONDITIONAL", category: Unreserved, bare_label: Bool.True },
		{ name: "configuration", token: "CONFIGURATION", category: Unreserved, bare_label: Bool.True },
		{ name: "conflict", token: "CONFLICT", category: Unreserved, bare_label: Bool.True },
		{ name: "connection", token: "CONNECTION", category: Unreserved, bare_label: Bool.True },
		{ name: "constraint", token: "CONSTRAINT", category: Reserved, bare_label: Bool.True },
		{ name: "constraints", token: "CONSTRAINTS", category: Unreserved, bare_label: Bool.True },
		{ name: "content", token: "CONTENT_P", category: Unreserved, bare_label: Bool.True },
		{ name: "continue", token: "CONTINUE_P", category: Unreserved, bare_label: Bool.True },
		{ name: "conversion", token: "CONVERSION_P", category: Unreserved, bare_label: Bool.True },
		{ name: "copy", token: "COPY", category: Unreserved, bare_label: Bool.True },
		{ name: "cost", token: "COST", category: Unreserved, bare_label: Bool.True },
		{ name: "create", token: "CREATE", category: Reserved, bare_label: Bool.False },
		{ name: "cross", token: "CROSS", category: TypeFuncName, bare_label: Bool.True },
		{ name: "csv", token: "CSV", category: Unreserved, bare_label: Bool.True },
		{ name: "cube", token: "CUBE", category: Unreserved, bare_label: Bool.True },
		{ name: "current", token: "CURRENT_P", category: Unreserved, bare_label: Bool.True },
		{ name: "current_catalog", token: "CURRENT_CATALOG", category: Reserved, bare_label: Bool.True },
		{ name: "current_date", token: "CURRENT_DATE", category: Reserved, bare_label: Bool.True },
		{ name: "current_role", token: "CURRENT_ROLE", category: Reserved, bare_label: Bool.True },
		{ name: "current_schema", token: "CURRENT_SCHEMA", category: TypeFuncName, bare_label: Bool.True },
		{ name: "current_time", token: "CURRENT_TIME", category: Reserved, bare_label: Bool.True },
		{ name: "current_timestamp", token: "CURRENT_TIMESTAMP", category: Reserved, bare_label: Bool.True },
		{ name: "current_user", token: "CURRENT_USER", category: Reserved, bare_label: Bool.True },
		{ name: "cursor", token: "CURSOR", category: Unreserved, bare_label: Bool.True },
		{ name: "cycle", token: "CYCLE", category: Unreserved, bare_label: Bool.True },
		{ name: "data", token: "DATA_P", category: Unreserved, bare_label: Bool.True },
		{ name: "database", token: "DATABASE", category: Unreserved, bare_label: Bool.True },
		{ name: "day", token: "DAY_P", category: Unreserved, bare_label: Bool.False },
		{ name: "deallocate", token: "DEALLOCATE", category: Unreserved, bare_label: Bool.True },
		{ name: "dec", token: "DEC", category: ColName, bare_label: Bool.True },
		{ name: "decimal", token: "DECIMAL_P", category: ColName, bare_label: Bool.True },
		{ name: "declare", token: "DECLARE", category: Unreserved, bare_label: Bool.True },
		{ name: "default", token: "DEFAULT", category: Reserved, bare_label: Bool.True },
		{ name: "defaults", token: "DEFAULTS", category: Unreserved, bare_label: Bool.True },
		{ name: "deferrable", token: "DEFERRABLE", category: Reserved, bare_label: Bool.True },
		{ name: "deferred", token: "DEFERRED", category: Unreserved, bare_label: Bool.True },
		{ name: "definer", token: "DEFINER", category: Unreserved, bare_label: Bool.True },
		{ name: "delete", token: "DELETE_P", category: Unreserved, bare_label: Bool.True },
		{ name: "delimiter", token: "DELIMITER", category: Unreserved, bare_label: Bool.True },
		{ name: "delimiters", token: "DELIMITERS", category: Unreserved, bare_label: Bool.True },
		{ name: "depends", token: "DEPENDS", category: Unreserved, bare_label: Bool.True },
		{ name: "depth", token: "DEPTH", category: Unreserved, bare_label: Bool.True },
		{ name: "desc", token: "DESC", category: Reserved, bare_label: Bool.True },
		{ name: "detach", token: "DETACH", category: Unreserved, bare_label: Bool.True },
		{ name: "dictionary", token: "DICTIONARY", category: Unreserved, bare_label: Bool.True },
		{ name: "disable", token: "DISABLE_P", category: Unreserved, bare_label: Bool.True },
		{ name: "discard", token: "DISCARD", category: Unreserved, bare_label: Bool.True },
		{ name: "distinct", token: "DISTINCT", category: Reserved, bare_label: Bool.True },
		{ name: "do", token: "DO", category: Reserved, bare_label: Bool.True },
		{ name: "document", token: "DOCUMENT_P", category: Unreserved, bare_label: Bool.True },
		{ name: "domain", token: "DOMAIN_P", category: Unreserved, bare_label: Bool.True },
		{ name: "double", token: "DOUBLE_P", category: Unreserved, bare_label: Bool.True },
		{ name: "drop", token: "DROP", category: Unreserved, bare_label: Bool.True },
		{ name: "each", token: "EACH", category: Unreserved, bare_label: Bool.True },
		{ name: "else", token: "ELSE", category: Reserved, bare_label: Bool.True },
		{ name: "empty", token: "EMPTY_P", category: Unreserved, bare_label: Bool.True },
		{ name: "enable", token: "ENABLE_P", category: Unreserved, bare_label: Bool.True },
		{ name: "encoding", token: "ENCODING", category: Unreserved, bare_label: Bool.True },
		{ name: "encrypted", token: "ENCRYPTED", category: Unreserved, bare_label: Bool.True },
		{ name: "end", token: "END_P", category: Reserved, bare_label: Bool.True },
		{ name: "enforced", token: "ENFORCED", category: Unreserved, bare_label: Bool.True },
		{ name: "enum", token: "ENUM_P", category: Unreserved, bare_label: Bool.True },
		{ name: "error", token: "ERROR_P", category: Unreserved, bare_label: Bool.True },
		{ name: "escape", token: "ESCAPE", category: Unreserved, bare_label: Bool.True },
		{ name: "event", token: "EVENT", category: Unreserved, bare_label: Bool.True },
		{ name: "except", token: "EXCEPT", category: Reserved, bare_label: Bool.False },
		{ name: "exclude", token: "EXCLUDE", category: Unreserved, bare_label: Bool.True },
		{ name: "excluding", token: "EXCLUDING", category: Unreserved, bare_label: Bool.True },
		{ name: "exclusive", token: "EXCLUSIVE", category: Unreserved, bare_label: Bool.True },
		{ name: "execute", token: "EXECUTE", category: Unreserved, bare_label: Bool.True },
		{ name: "exists", token: "EXISTS", category: ColName, bare_label: Bool.True },
		{ name: "explain", token: "EXPLAIN", category: Unreserved, bare_label: Bool.True },
		{ name: "expression", token: "EXPRESSION", category: Unreserved, bare_label: Bool.True },
		{ name: "extension", token: "EXTENSION", category: Unreserved, bare_label: Bool.True },
		{ name: "external", token: "EXTERNAL", category: Unreserved, bare_label: Bool.True },
		{ name: "extract", token: "EXTRACT", category: ColName, bare_label: Bool.True },
		{ name: "false", token: "FALSE_P", category: Reserved, bare_label: Bool.True },
		{ name: "family", token: "FAMILY", category: Unreserved, bare_label: Bool.True },
		{ name: "fetch", token: "FETCH", category: Reserved, bare_label: Bool.False },
		{ name: "filter", token: "FILTER", category: Unreserved, bare_label: Bool.False },
		{ name: "finalize", token: "FINALIZE", category: Unreserved, bare_label: Bool.True },
		{ name: "first", token: "FIRST_P", category: Unreserved, bare_label: Bool.True },
		{ name: "float", token: "FLOAT_P", category: ColName, bare_label: Bool.True },
		{ name: "following", token: "FOLLOWING", category: Unreserved, bare_label: Bool.True },
		{ name: "for", token: "FOR", category: Reserved, bare_label: Bool.False },
		{ name: "force", token: "FORCE", category: Unreserved, bare_label: Bool.True },
		{ name: "foreign", token: "FOREIGN", category: Reserved, bare_label: Bool.True },
		{ name: "format", token: "FORMAT", category: Unreserved, bare_label: Bool.True },
		{ name: "forward", token: "FORWARD", category: Unreserved, bare_label: Bool.True },
		{ name: "freeze", token: "FREEZE", category: TypeFuncName, bare_label: Bool.True },
		{ name: "from", token: "FROM", category: Reserved, bare_label: Bool.False },
		{ name: "full", token: "FULL", category: TypeFuncName, bare_label: Bool.True },
		{ name: "function", token: "FUNCTION", category: Unreserved, bare_label: Bool.True },
		{ name: "functions", token: "FUNCTIONS", category: Unreserved, bare_label: Bool.True },
		{ name: "generated", token: "GENERATED", category: Unreserved, bare_label: Bool.True },
		{ name: "global", token: "GLOBAL", category: Unreserved, bare_label: Bool.True },
		{ name: "grant", token: "GRANT", category: Reserved, bare_label: Bool.False },
		{ name: "granted", token: "GRANTED", category: Unreserved, bare_label: Bool.True },
		{ name: "greatest", token: "GREATEST", category: ColName, bare_label: Bool.True },
		{ name: "group", token: "GROUP_P", category: Reserved, bare_label: Bool.False },
		{ name: "grouping", token: "GROUPING", category: ColName, bare_label: Bool.True },
		{ name: "groups", token: "GROUPS", category: Unreserved, bare_label: Bool.True },
		{ name: "handler", token: "HANDLER", category: Unreserved, bare_label: Bool.True },
		{ name: "having", token: "HAVING", category: Reserved, bare_label: Bool.False },
		{ name: "header", token: "HEADER_P", category: Unreserved, bare_label: Bool.True },
		{ name: "hold", token: "HOLD", category: Unreserved, bare_label: Bool.True },
		{ name: "hour", token: "HOUR_P", category: Unreserved, bare_label: Bool.False },
		{ name: "identity", token: "IDENTITY_P", category: Unreserved, bare_label: Bool.True },
		{ name: "if", token: "IF_P", category: Unreserved, bare_label: Bool.True },
		{ name: "ilike", token: "ILIKE", category: TypeFuncName, bare_label: Bool.True },
		{ name: "immediate", token: "IMMEDIATE", category: Unreserved, bare_label: Bool.True },
		{ name: "immutable", token: "IMMUTABLE", category: Unreserved, bare_label: Bool.True },
		{ name: "implicit", token: "IMPLICIT_P", category: Unreserved, bare_label: Bool.True },
		{ name: "import", token: "IMPORT_P", category: Unreserved, bare_label: Bool.True },
		{ name: "in", token: "IN_P", category: Reserved, bare_label: Bool.True },
		{ name: "include", token: "INCLUDE", category: Unreserved, bare_label: Bool.True },
		{ name: "including", token: "INCLUDING", category: Unreserved, bare_label: Bool.True },
		{ name: "increment", token: "INCREMENT", category: Unreserved, bare_label: Bool.True },
		{ name: "indent", token: "INDENT", category: Unreserved, bare_label: Bool.True },
		{ name: "index", token: "INDEX", category: Unreserved, bare_label: Bool.True },
		{ name: "indexes", token: "INDEXES", category: Unreserved, bare_label: Bool.True },
		{ name: "inherit", token: "INHERIT", category: Unreserved, bare_label: Bool.True },
		{ name: "inherits", token: "INHERITS", category: Unreserved, bare_label: Bool.True },
		{ name: "initially", token: "INITIALLY", category: Reserved, bare_label: Bool.True },
		{ name: "inline", token: "INLINE_P", category: Unreserved, bare_label: Bool.True },
		{ name: "inner", token: "INNER_P", category: TypeFuncName, bare_label: Bool.True },
		{ name: "inout", token: "INOUT", category: ColName, bare_label: Bool.True },
		{ name: "input", token: "INPUT_P", category: Unreserved, bare_label: Bool.True },
		{ name: "insensitive", token: "INSENSITIVE", category: Unreserved, bare_label: Bool.True },
		{ name: "insert", token: "INSERT", category: Unreserved, bare_label: Bool.True },
		{ name: "instead", token: "INSTEAD", category: Unreserved, bare_label: Bool.True },
		{ name: "int", token: "INT_P", category: ColName, bare_label: Bool.True },
		{ name: "integer", token: "INTEGER", category: ColName, bare_label: Bool.True },
		{ name: "intersect", token: "INTERSECT", category: Reserved, bare_label: Bool.False },
		{ name: "interval", token: "INTERVAL", category: ColName, bare_label: Bool.True },
		{ name: "into", token: "INTO", category: Reserved, bare_label: Bool.False },
		{ name: "invoker", token: "INVOKER", category: Unreserved, bare_label: Bool.True },
		{ name: "is", token: "IS", category: TypeFuncName, bare_label: Bool.True },
		{ name: "isnull", token: "ISNULL", category: TypeFuncName, bare_label: Bool.False },
		{ name: "isolation", token: "ISOLATION", category: Unreserved, bare_label: Bool.True },
		{ name: "join", token: "JOIN", category: TypeFuncName, bare_label: Bool.True },
		{ name: "json", token: "JSON", category: ColName, bare_label: Bool.True },
		{ name: "json_array", token: "JSON_ARRAY", category: ColName, bare_label: Bool.True },
		{ name: "json_arrayagg", token: "JSON_ARRAYAGG", category: ColName, bare_label: Bool.True },
		{ name: "json_exists", token: "JSON_EXISTS", category: ColName, bare_label: Bool.True },
		{ name: "json_object", token: "JSON_OBJECT", category: ColName, bare_label: Bool.True },
		{ name: "json_objectagg", token: "JSON_OBJECTAGG", category: ColName, bare_label: Bool.True },
		{ name: "json_query", token: "JSON_QUERY", category: ColName, bare_label: Bool.True },
		{ name: "json_scalar", token: "JSON_SCALAR", category: ColName, bare_label: Bool.True },
		{ name: "json_serialize", token: "JSON_SERIALIZE", category: ColName, bare_label: Bool.True },
		{ name: "json_table", token: "JSON_TABLE", category: ColName, bare_label: Bool.True },
		{ name: "json_value", token: "JSON_VALUE", category: ColName, bare_label: Bool.True },
		{ name: "keep", token: "KEEP", category: Unreserved, bare_label: Bool.True },
		{ name: "key", token: "KEY", category: Unreserved, bare_label: Bool.True },
		{ name: "keys", token: "KEYS", category: Unreserved, bare_label: Bool.True },
		{ name: "label", token: "LABEL", category: Unreserved, bare_label: Bool.True },
		{ name: "language", token: "LANGUAGE", category: Unreserved, bare_label: Bool.True },
		{ name: "large", token: "LARGE_P", category: Unreserved, bare_label: Bool.True },
		{ name: "last", token: "LAST_P", category: Unreserved, bare_label: Bool.True },
		{ name: "lateral", token: "LATERAL_P", category: Reserved, bare_label: Bool.True },
		{ name: "leading", token: "LEADING", category: Reserved, bare_label: Bool.True },
		{ name: "leakproof", token: "LEAKPROOF", category: Unreserved, bare_label: Bool.True },
		{ name: "least", token: "LEAST", category: ColName, bare_label: Bool.True },
		{ name: "left", token: "LEFT", category: TypeFuncName, bare_label: Bool.True },
		{ name: "level", token: "LEVEL", category: Unreserved, bare_label: Bool.True },
		{ name: "like", token: "LIKE", category: TypeFuncName, bare_label: Bool.True },
		{ name: "limit", token: "LIMIT", category: Reserved, bare_label: Bool.False },
		{ name: "listen", token: "LISTEN", category: Unreserved, bare_label: Bool.True },
		{ name: "load", token: "LOAD", category: Unreserved, bare_label: Bool.True },
		{ name: "local", token: "LOCAL", category: Unreserved, bare_label: Bool.True },
		{ name: "localtime", token: "LOCALTIME", category: Reserved, bare_label: Bool.True },
		{ name: "localtimestamp", token: "LOCALTIMESTAMP", category: Reserved, bare_label: Bool.True },
		{ name: "location", token: "LOCATION", category: Unreserved, bare_label: Bool.True },
		{ name: "lock", token: "LOCK_P", category: Unreserved, bare_label: Bool.True },
		{ name: "locked", token: "LOCKED", category: Unreserved, bare_label: Bool.True },
		{ name: "logged", token: "LOGGED", category: Unreserved, bare_label: Bool.True },
		{ name: "mapping", token: "MAPPING", category: Unreserved, bare_label: Bool.True },
		{ name: "match", token: "MATCH", category: Unreserved, bare_label: Bool.True },
		{ name: "matched", token: "MATCHED", category: Unreserved, bare_label: Bool.True },
		{ name: "materialized", token: "MATERIALIZED", category: Unreserved, bare_label: Bool.True },
		{ name: "maxvalue", token: "MAXVALUE", category: Unreserved, bare_label: Bool.True },
		{ name: "merge", token: "MERGE", category: Unreserved, bare_label: Bool.True },
		{ name: "merge_action", token: "MERGE_ACTION", category: ColName, bare_label: Bool.True },
		{ name: "method", token: "METHOD", category: Unreserved, bare_label: Bool.True },
		{ name: "minute", token: "MINUTE_P", category: Unreserved, bare_label: Bool.False },
		{ name: "minvalue", token: "MINVALUE", category: Unreserved, bare_label: Bool.True },
		{ name: "mode", token: "MODE", category: Unreserved, bare_label: Bool.True },
		{ name: "month", token: "MONTH_P", category: Unreserved, bare_label: Bool.False },
		{ name: "move", token: "MOVE", category: Unreserved, bare_label: Bool.True },
		{ name: "name", token: "NAME_P", category: Unreserved, bare_label: Bool.True },
		{ name: "names", token: "NAMES", category: Unreserved, bare_label: Bool.True },
		{ name: "national", token: "NATIONAL", category: ColName, bare_label: Bool.True },
		{ name: "natural", token: "NATURAL", category: TypeFuncName, bare_label: Bool.True },
		{ name: "nchar", token: "NCHAR", category: ColName, bare_label: Bool.True },
		{ name: "nested", token: "NESTED", category: Unreserved, bare_label: Bool.True },
		{ name: "new", token: "NEW", category: Unreserved, bare_label: Bool.True },
		{ name: "next", token: "NEXT", category: Unreserved, bare_label: Bool.True },
		{ name: "nfc", token: "NFC", category: Unreserved, bare_label: Bool.True },
		{ name: "nfd", token: "NFD", category: Unreserved, bare_label: Bool.True },
		{ name: "nfkc", token: "NFKC", category: Unreserved, bare_label: Bool.True },
		{ name: "nfkd", token: "NFKD", category: Unreserved, bare_label: Bool.True },
		{ name: "no", token: "NO", category: Unreserved, bare_label: Bool.True },
		{ name: "none", token: "NONE", category: ColName, bare_label: Bool.True },
		{ name: "normalize", token: "NORMALIZE", category: ColName, bare_label: Bool.True },
		{ name: "normalized", token: "NORMALIZED", category: Unreserved, bare_label: Bool.True },
		{ name: "not", token: "NOT", category: Reserved, bare_label: Bool.True },
		{ name: "nothing", token: "NOTHING", category: Unreserved, bare_label: Bool.True },
		{ name: "notify", token: "NOTIFY", category: Unreserved, bare_label: Bool.True },
		{ name: "notnull", token: "NOTNULL", category: TypeFuncName, bare_label: Bool.False },
		{ name: "nowait", token: "NOWAIT", category: Unreserved, bare_label: Bool.True },
		{ name: "null", token: "NULL_P", category: Reserved, bare_label: Bool.True },
		{ name: "nullif", token: "NULLIF", category: ColName, bare_label: Bool.True },
		{ name: "nulls", token: "NULLS_P", category: Unreserved, bare_label: Bool.True },
		{ name: "numeric", token: "NUMERIC", category: ColName, bare_label: Bool.True },
		{ name: "object", token: "OBJECT_P", category: Unreserved, bare_label: Bool.True },
		{ name: "objects", token: "OBJECTS_P", category: Unreserved, bare_label: Bool.True },
		{ name: "of", token: "OF", category: Unreserved, bare_label: Bool.True },
		{ name: "off", token: "OFF", category: Unreserved, bare_label: Bool.True },
		{ name: "offset", token: "OFFSET", category: Reserved, bare_label: Bool.False },
		{ name: "oids", token: "OIDS", category: Unreserved, bare_label: Bool.True },
		{ name: "old", token: "OLD", category: Unreserved, bare_label: Bool.True },
		{ name: "omit", token: "OMIT", category: Unreserved, bare_label: Bool.True },
		{ name: "on", token: "ON", category: Reserved, bare_label: Bool.False },
		{ name: "only", token: "ONLY", category: Reserved, bare_label: Bool.True },
		{ name: "operator", token: "OPERATOR", category: Unreserved, bare_label: Bool.True },
		{ name: "option", token: "OPTION", category: Unreserved, bare_label: Bool.True },
		{ name: "options", token: "OPTIONS", category: Unreserved, bare_label: Bool.True },
		{ name: "or", token: "OR", category: Reserved, bare_label: Bool.True },
		{ name: "order", token: "ORDER", category: Reserved, bare_label: Bool.False },
		{ name: "ordinality", token: "ORDINALITY", category: Unreserved, bare_label: Bool.True },
		{ name: "others", token: "OTHERS", category: Unreserved, bare_label: Bool.True },
		{ name: "out", token: "OUT_P", category: ColName, bare_label: Bool.True },
		{ name: "outer", token: "OUTER_P", category: TypeFuncName, bare_label: Bool.True },
		{ name: "over", token: "OVER", category: Unreserved, bare_label: Bool.False },
		{ name: "overlaps", token: "OVERLAPS", category: TypeFuncName, bare_label: Bool.False },
		{ name: "overlay", token: "OVERLAY", category: ColName, bare_label: Bool.True },
		{ name: "overriding", token: "OVERRIDING", category: Unreserved, bare_label: Bool.True },
		{ name: "owned", token: "OWNED", category: Unreserved, bare_label: Bool.True },
		{ name: "owner", token: "OWNER", category: Unreserved, bare_label: Bool.True },
		{ name: "parallel", token: "PARALLEL", category: Unreserved, bare_label: Bool.True },
		{ name: "parameter", token: "PARAMETER", category: Unreserved, bare_label: Bool.True },
		{ name: "parser", token: "PARSER", category: Unreserved, bare_label: Bool.True },
		{ name: "partial", token: "PARTIAL", category: Unreserved, bare_label: Bool.True },
		{ name: "partition", token: "PARTITION", category: Unreserved, bare_label: Bool.True },
		{ name: "passing", token: "PASSING", category: Unreserved, bare_label: Bool.True },
		{ name: "password", token: "PASSWORD", category: Unreserved, bare_label: Bool.True },
		{ name: "path", token: "PATH", category: Unreserved, bare_label: Bool.True },
		{ name: "period", token: "PERIOD", category: Unreserved, bare_label: Bool.True },
		{ name: "placing", token: "PLACING", category: Reserved, bare_label: Bool.True },
		{ name: "plan", token: "PLAN", category: Unreserved, bare_label: Bool.True },
		{ name: "plans", token: "PLANS", category: Unreserved, bare_label: Bool.True },
		{ name: "policy", token: "POLICY", category: Unreserved, bare_label: Bool.True },
		{ name: "position", token: "POSITION", category: ColName, bare_label: Bool.True },
		{ name: "preceding", token: "PRECEDING", category: Unreserved, bare_label: Bool.True },
		{ name: "precision", token: "PRECISION", category: ColName, bare_label: Bool.False },
		{ name: "prepare", token: "PREPARE", category: Unreserved, bare_label: Bool.True },
		{ name: "prepared", token: "PREPARED", category: Unreserved, bare_label: Bool.True },
		{ name: "preserve", token: "PRESERVE", category: Unreserved, bare_label: Bool.True },
		{ name: "primary", token: "PRIMARY", category: Reserved, bare_label: Bool.True },
		{ name: "prior", token: "PRIOR", category: Unreserved, bare_label: Bool.True },
		{ name: "privileges", token: "PRIVILEGES", category: Unreserved, bare_label: Bool.True },
		{ name: "procedural", token: "PROCEDURAL", category: Unreserved, bare_label: Bool.True },
		{ name: "procedure", token: "PROCEDURE", category: Unreserved, bare_label: Bool.True },
		{ name: "procedures", token: "PROCEDURES", category: Unreserved, bare_label: Bool.True },
		{ name: "program", token: "PROGRAM", category: Unreserved, bare_label: Bool.True },
		{ name: "publication", token: "PUBLICATION", category: Unreserved, bare_label: Bool.True },
		{ name: "quote", token: "QUOTE", category: Unreserved, bare_label: Bool.True },
		{ name: "quotes", token: "QUOTES", category: Unreserved, bare_label: Bool.True },
		{ name: "range", token: "RANGE", category: Unreserved, bare_label: Bool.True },
		{ name: "read", token: "READ", category: Unreserved, bare_label: Bool.True },
		{ name: "real", token: "REAL", category: ColName, bare_label: Bool.True },
		{ name: "reassign", token: "REASSIGN", category: Unreserved, bare_label: Bool.True },
		{ name: "recursive", token: "RECURSIVE", category: Unreserved, bare_label: Bool.True },
		{ name: "ref", token: "REF_P", category: Unreserved, bare_label: Bool.True },
		{ name: "references", token: "REFERENCES", category: Reserved, bare_label: Bool.True },
		{ name: "referencing", token: "REFERENCING", category: Unreserved, bare_label: Bool.True },
		{ name: "refresh", token: "REFRESH", category: Unreserved, bare_label: Bool.True },
		{ name: "reindex", token: "REINDEX", category: Unreserved, bare_label: Bool.True },
		{ name: "relative", token: "RELATIVE_P", category: Unreserved, bare_label: Bool.True },
		{ name: "release", token: "RELEASE", category: Unreserved, bare_label: Bool.True },
		{ name: "rename", token: "RENAME", category: Unreserved, bare_label: Bool.True },
		{ name: "repeatable", token: "REPEATABLE", category: Unreserved, bare_label: Bool.True },
		{ name: "replace", token: "REPLACE", category: Unreserved, bare_label: Bool.True },
		{ name: "replica", token: "REPLICA", category: Unreserved, bare_label: Bool.True },
		{ name: "reset", token: "RESET", category: Unreserved, bare_label: Bool.True },
		{ name: "restart", token: "RESTART", category: Unreserved, bare_label: Bool.True },
		{ name: "restrict", token: "RESTRICT", category: Unreserved, bare_label: Bool.True },
		{ name: "return", token: "RETURN", category: Unreserved, bare_label: Bool.True },
		{ name: "returning", token: "RETURNING", category: Reserved, bare_label: Bool.False },
		{ name: "returns", token: "RETURNS", category: Unreserved, bare_label: Bool.True },
		{ name: "revoke", token: "REVOKE", category: Unreserved, bare_label: Bool.True },
		{ name: "right", token: "RIGHT", category: TypeFuncName, bare_label: Bool.True },
		{ name: "role", token: "ROLE", category: Unreserved, bare_label: Bool.True },
		{ name: "rollback", token: "ROLLBACK", category: Unreserved, bare_label: Bool.True },
		{ name: "rollup", token: "ROLLUP", category: Unreserved, bare_label: Bool.True },
		{ name: "routine", token: "ROUTINE", category: Unreserved, bare_label: Bool.True },
		{ name: "routines", token: "ROUTINES", category: Unreserved, bare_label: Bool.True },
		{ name: "row", token: "ROW", category: ColName, bare_label: Bool.True },
		{ name: "rows", token: "ROWS", category: Unreserved, bare_label: Bool.True },
		{ name: "rule", token: "RULE", category: Unreserved, bare_label: Bool.True },
		{ name: "savepoint", token: "SAVEPOINT", category: Unreserved, bare_label: Bool.True },
		{ name: "scalar", token: "SCALAR", category: Unreserved, bare_label: Bool.True },
		{ name: "schema", token: "SCHEMA", category: Unreserved, bare_label: Bool.True },
		{ name: "schemas", token: "SCHEMAS", category: Unreserved, bare_label: Bool.True },
		{ name: "scroll", token: "SCROLL", category: Unreserved, bare_label: Bool.True },
		{ name: "search", token: "SEARCH", category: Unreserved, bare_label: Bool.True },
		{ name: "second", token: "SECOND_P", category: Unreserved, bare_label: Bool.False },
		{ name: "security", token: "SECURITY", category: Unreserved, bare_label: Bool.True },
		{ name: "select", token: "SELECT", category: Reserved, bare_label: Bool.True },
		{ name: "sequence", token: "SEQUENCE", category: Unreserved, bare_label: Bool.True },
		{ name: "sequences", token: "SEQUENCES", category: Unreserved, bare_label: Bool.True },
		{ name: "serializable", token: "SERIALIZABLE", category: Unreserved, bare_label: Bool.True },
		{ name: "server", token: "SERVER", category: Unreserved, bare_label: Bool.True },
		{ name: "session", token: "SESSION", category: Unreserved, bare_label: Bool.True },
		{ name: "session_user", token: "SESSION_USER", category: Reserved, bare_label: Bool.True },
		{ name: "set", token: "SET", category: Unreserved, bare_label: Bool.True },
		{ name: "setof", token: "SETOF", category: ColName, bare_label: Bool.True },
		{ name: "sets", token: "SETS", category: Unreserved, bare_label: Bool.True },
		{ name: "share", token: "SHARE", category: Unreserved, bare_label: Bool.True },
		{ name: "show", token: "SHOW", category: Unreserved, bare_label: Bool.True },
		{ name: "similar", token: "SIMILAR", category: TypeFuncName, bare_label: Bool.True },
		{ name: "simple", token: "SIMPLE", category: Unreserved, bare_label: Bool.True },
		{ name: "skip", token: "SKIP", category: Unreserved, bare_label: Bool.True },
		{ name: "smallint", token: "SMALLINT", category: ColName, bare_label: Bool.True },
		{ name: "snapshot", token: "SNAPSHOT", category: Unreserved, bare_label: Bool.True },
		{ name: "some", token: "SOME", category: Reserved, bare_label: Bool.True },
		{ name: "source", token: "SOURCE", category: Unreserved, bare_label: Bool.True },
		{ name: "sql", token: "SQL_P", category: Unreserved, bare_label: Bool.True },
		{ name: "stable", token: "STABLE", category: Unreserved, bare_label: Bool.True },
		{ name: "standalone", token: "STANDALONE_P", category: Unreserved, bare_label: Bool.True },
		{ name: "start", token: "START", category: Unreserved, bare_label: Bool.True },
		{ name: "statement", token: "STATEMENT", category: Unreserved, bare_label: Bool.True },
		{ name: "statistics", token: "STATISTICS", category: Unreserved, bare_label: Bool.True },
		{ name: "stdin", token: "STDIN", category: Unreserved, bare_label: Bool.True },
		{ name: "stdout", token: "STDOUT", category: Unreserved, bare_label: Bool.True },
		{ name: "storage", token: "STORAGE", category: Unreserved, bare_label: Bool.True },
		{ name: "stored", token: "STORED", category: Unreserved, bare_label: Bool.True },
		{ name: "strict", token: "STRICT_P", category: Unreserved, bare_label: Bool.True },
		{ name: "string", token: "STRING_P", category: Unreserved, bare_label: Bool.True },
		{ name: "strip", token: "STRIP_P", category: Unreserved, bare_label: Bool.True },
		{ name: "subscription", token: "SUBSCRIPTION", category: Unreserved, bare_label: Bool.True },
		{ name: "substring", token: "SUBSTRING", category: ColName, bare_label: Bool.True },
		{ name: "support", token: "SUPPORT", category: Unreserved, bare_label: Bool.True },
		{ name: "symmetric", token: "SYMMETRIC", category: Reserved, bare_label: Bool.True },
		{ name: "sysid", token: "SYSID", category: Unreserved, bare_label: Bool.True },
		{ name: "system", token: "SYSTEM_P", category: Unreserved, bare_label: Bool.True },
		{ name: "system_user", token: "SYSTEM_USER", category: Reserved, bare_label: Bool.True },
		{ name: "table", token: "TABLE", category: Reserved, bare_label: Bool.True },
		{ name: "tables", token: "TABLES", category: Unreserved, bare_label: Bool.True },
		{ name: "tablesample", token: "TABLESAMPLE", category: TypeFuncName, bare_label: Bool.True },
		{ name: "tablespace", token: "TABLESPACE", category: Unreserved, bare_label: Bool.True },
		{ name: "target", token: "TARGET", category: Unreserved, bare_label: Bool.True },
		{ name: "temp", token: "TEMP", category: Unreserved, bare_label: Bool.True },
		{ name: "template", token: "TEMPLATE", category: Unreserved, bare_label: Bool.True },
		{ name: "temporary", token: "TEMPORARY", category: Unreserved, bare_label: Bool.True },
		{ name: "text", token: "TEXT_P", category: Unreserved, bare_label: Bool.True },
		{ name: "then", token: "THEN", category: Reserved, bare_label: Bool.True },
		{ name: "ties", token: "TIES", category: Unreserved, bare_label: Bool.True },
		{ name: "time", token: "TIME", category: ColName, bare_label: Bool.True },
		{ name: "timestamp", token: "TIMESTAMP", category: ColName, bare_label: Bool.True },
		{ name: "to", token: "TO", category: Reserved, bare_label: Bool.False },
		{ name: "trailing", token: "TRAILING", category: Reserved, bare_label: Bool.True },
		{ name: "transaction", token: "TRANSACTION", category: Unreserved, bare_label: Bool.True },
		{ name: "transform", token: "TRANSFORM", category: Unreserved, bare_label: Bool.True },
		{ name: "treat", token: "TREAT", category: ColName, bare_label: Bool.True },
		{ name: "trigger", token: "TRIGGER", category: Unreserved, bare_label: Bool.True },
		{ name: "trim", token: "TRIM", category: ColName, bare_label: Bool.True },
		{ name: "true", token: "TRUE_P", category: Reserved, bare_label: Bool.True },
		{ name: "truncate", token: "TRUNCATE", category: Unreserved, bare_label: Bool.True },
		{ name: "trusted", token: "TRUSTED", category: Unreserved, bare_label: Bool.True },
		{ name: "type", token: "TYPE_P", category: Unreserved, bare_label: Bool.True },
		{ name: "types", token: "TYPES_P", category: Unreserved, bare_label: Bool.True },
		{ name: "uescape", token: "UESCAPE", category: Unreserved, bare_label: Bool.True },
		{ name: "unbounded", token: "UNBOUNDED", category: Unreserved, bare_label: Bool.True },
		{ name: "uncommitted", token: "UNCOMMITTED", category: Unreserved, bare_label: Bool.True },
		{ name: "unconditional", token: "UNCONDITIONAL", category: Unreserved, bare_label: Bool.True },
		{ name: "unencrypted", token: "UNENCRYPTED", category: Unreserved, bare_label: Bool.True },
		{ name: "union", token: "UNION", category: Reserved, bare_label: Bool.False },
		{ name: "unique", token: "UNIQUE", category: Reserved, bare_label: Bool.True },
		{ name: "unknown", token: "UNKNOWN", category: Unreserved, bare_label: Bool.True },
		{ name: "unlisten", token: "UNLISTEN", category: Unreserved, bare_label: Bool.True },
		{ name: "unlogged", token: "UNLOGGED", category: Unreserved, bare_label: Bool.True },
		{ name: "until", token: "UNTIL", category: Unreserved, bare_label: Bool.True },
		{ name: "update", token: "UPDATE", category: Unreserved, bare_label: Bool.True },
		{ name: "user", token: "USER", category: Reserved, bare_label: Bool.True },
		{ name: "using", token: "USING", category: Reserved, bare_label: Bool.True },
		{ name: "vacuum", token: "VACUUM", category: Unreserved, bare_label: Bool.True },
		{ name: "valid", token: "VALID", category: Unreserved, bare_label: Bool.True },
		{ name: "validate", token: "VALIDATE", category: Unreserved, bare_label: Bool.True },
		{ name: "validator", token: "VALIDATOR", category: Unreserved, bare_label: Bool.True },
		{ name: "value", token: "VALUE_P", category: Unreserved, bare_label: Bool.True },
		{ name: "values", token: "VALUES", category: ColName, bare_label: Bool.True },
		{ name: "varchar", token: "VARCHAR", category: ColName, bare_label: Bool.True },
		{ name: "variadic", token: "VARIADIC", category: Reserved, bare_label: Bool.True },
		{ name: "varying", token: "VARYING", category: Unreserved, bare_label: Bool.False },
		{ name: "verbose", token: "VERBOSE", category: TypeFuncName, bare_label: Bool.True },
		{ name: "version", token: "VERSION_P", category: Unreserved, bare_label: Bool.True },
		{ name: "view", token: "VIEW", category: Unreserved, bare_label: Bool.True },
		{ name: "views", token: "VIEWS", category: Unreserved, bare_label: Bool.True },
		{ name: "virtual", token: "VIRTUAL", category: Unreserved, bare_label: Bool.True },
		{ name: "volatile", token: "VOLATILE", category: Unreserved, bare_label: Bool.True },
		{ name: "when", token: "WHEN", category: Reserved, bare_label: Bool.True },
		{ name: "where", token: "WHERE", category: Reserved, bare_label: Bool.False },
		{ name: "whitespace", token: "WHITESPACE_P", category: Unreserved, bare_label: Bool.True },
		{ name: "window", token: "WINDOW", category: Reserved, bare_label: Bool.False },
		{ name: "with", token: "WITH", category: Reserved, bare_label: Bool.False },
		{ name: "within", token: "WITHIN", category: Unreserved, bare_label: Bool.False },
		{ name: "without", token: "WITHOUT", category: Unreserved, bare_label: Bool.False },
		{ name: "work", token: "WORK", category: Unreserved, bare_label: Bool.True },
		{ name: "wrapper", token: "WRAPPER", category: Unreserved, bare_label: Bool.True },
		{ name: "write", token: "WRITE", category: Unreserved, bare_label: Bool.True },
		{ name: "xml", token: "XML_P", category: Unreserved, bare_label: Bool.True },
		{ name: "xmlattributes", token: "XMLATTRIBUTES", category: ColName, bare_label: Bool.True },
		{ name: "xmlconcat", token: "XMLCONCAT", category: ColName, bare_label: Bool.True },
		{ name: "xmlelement", token: "XMLELEMENT", category: ColName, bare_label: Bool.True },
		{ name: "xmlexists", token: "XMLEXISTS", category: ColName, bare_label: Bool.True },
		{ name: "xmlforest", token: "XMLFOREST", category: ColName, bare_label: Bool.True },
		{ name: "xmlnamespaces", token: "XMLNAMESPACES", category: ColName, bare_label: Bool.True },
		{ name: "xmlparse", token: "XMLPARSE", category: ColName, bare_label: Bool.True },
		{ name: "xmlpi", token: "XMLPI", category: ColName, bare_label: Bool.True },
		{ name: "xmlroot", token: "XMLROOT", category: ColName, bare_label: Bool.True },
		{ name: "xmlserialize", token: "XMLSERIALIZE", category: ColName, bare_label: Bool.True },
		{ name: "xmltable", token: "XMLTABLE", category: ColName, bare_label: Bool.True },
		{ name: "year", token: "YEAR_P", category: Unreserved, bare_label: Bool.False },
		{ name: "yes", token: "YES_P", category: Unreserved, bare_label: Bool.True },
		{ name: "zone", token: "ZONE", category: Unreserved, bare_label: Bool.True },
	]

	## The keyword a word is, if any. Like the server, only ASCII letters
	## are folded to lower case, so a word with any other character is never
	## a keyword.
	lookup : Str -> Try(U64, [NotKeyword])
	lookup = |word| {
		bytes = word.to_utf8()
		if bytes.len() > max_len {
			return Err(NotKeyword)
		}
		lower = Str.from_utf8_lossy(bytes.map(|b| if b >= 'A' and b <= 'Z' b + 32 else b))
		index.get(lower).map_err(|_| NotKeyword)
	}

	## The keyword at an index from [Keywords.lookup].
	get : U64 -> Keywords.Keyword
	get = |i| Keywords.all.get(i) ?? { name: "", token: "", category: Unreserved, bare_label: Bool.False }
}

## The longest keyword, so longer words skip the lookup.
max_len : U64
max_len = 17

index : Dict(Str, U64)
index = Dict.from_list(Keywords.all.map_with_index(|k, i| (k.name, i)))

expect Keywords.lookup("SELECT").map_ok(|i| Keywords.get(i).token) == Ok("SELECT")
expect Keywords.lookup("null").map_ok(|i| Keywords.get(i).token) == Ok("NULL_P")
expect Keywords.lookup("school_id") == Err(NotKeyword)
expect Keywords.all.len() == 494
expect Keywords.all.fold(0, |m, k| if k.name.to_utf8().len() > m k.name.to_utf8().len() else m) == max_len
